# Generated by Django 4.2.16 on 2024-10-02 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motoSpektakl', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='BlogComment',
        ),
        migrations.AlterModelTable(
            name='blogcomment',
            table=None,
        ),
    ]
