# Generated by Django 4.2.16 on 2024-09-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoSpektakl', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('nowości', 'Nowości motoryzacyjne'), ('recenzje', 'Recenzje pojazdów'), ('poradniki', 'Poradniki techniczne'), ('historie', 'Moje prywatne historie')], default='nowości', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
