# Generated by Django 4.2.16 on 2024-10-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoSpektakl', '0005_userprofile_description_userprofile_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vehicle',
        ),
    ]
