# Generated by Django 4.2.16 on 2024-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoSpektakl', '0006_remove_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
